/** Defaults dos prompts do bot — usados no seed e como fallback */

export interface PromptDef {
  key: string;
  label: string;
  category: string;
  content: string;
  hint?: string;
}

/**
 * Linguagem do atendimento WhatsApp da Garagem do Ka.
 * Os templates são curtos para que o cliente sempre saiba o próximo passo.
 */
export const BOT_PROMPT_DEFAULTS: PromptDef[] = [
  {
    key: "etapa1_welcome",
    label: "Boas-vindas (etapa 1)",
    category: "fluxo",
    hint: "{businessName}, {address}, {hours}",
    content: "Olá! Você está falando com a *{businessName}* 🚗\n\nSou a assistente virtual com IA da nossa equipe. Posso orientar o melhor cuidado para o seu veículo, informar uma estimativa e organizar seu agendamento.\n\nTrabalhamos com lavagem técnica, polimento, proteção de pintura, higienização interna e detalhamento automotivo.\n\n📍 {address}\n🕒 {hours}\n\nPara iniciar seu atendimento, como você prefere ser chamado(a)?",
  },
  {
    key: "initial_schedule_name_request",
    label: "Agendamento identificado — solicitar nome",
    category: "fluxo",
    hint: "{serviceLine}",
    content: "✅ Entendi: você quer agendar{serviceLine}.\n\nAntes de buscar os melhores horários, como posso te chamar?\n_Envie somente seu primeiro nome._",
  },
  {
    key: "initial_request_summary",
    label: "Resumo inteligente da primeira mensagem",
    category: "fluxo",
    hint: "{name}, {vehicle}, {service}, {dateLine}, {periodLine}",
    content: "✨ *Entendi seu pedido, {name}.*\n\nConfirma se organizei tudo corretamente?\n\n👤 *Cliente:* {name}\n🚗 *Veículo:* {vehicle}\n🛠️ *Serviço:* {service}\n{dateLine}\n{periodLine}\n\n*1* ✅ Está certo, continuar\n*2* ✏️ Quero corrigir uma informação\n\n_Você pode responder com o número ou escrever naturalmente._",
  },
  {
    key: "etapa2_main_menu",
    label: "Menu principal (etapa 2)",
    category: "fluxo",
    hint: "{clientName}, {menu}",
    content: "Olá, *{clientName}*. Qual cuidado seu veículo precisa hoje?\n\nVocê pode descrever o caso em uma mensagem livre — nossa IA ajuda a indicar o serviço — ou escolher uma opção:\n\n{menu}\n\nPara falar diretamente com um especialista da equipe, responda *9*.\n_A qualquer momento, envie *menu* para recomeçar._",
  },
  {
    key: "service_action_menu",
    label: "Ações após detalhe do serviço",
    category: "fluxo",
    content: "Como deseja seguir?\n\n*1* 📅 Agendar este serviço\n*2* ↩️ Ver outros serviços\n*3* 💬 Tirar uma dúvida\n*4* 👤 Falar com um especialista\n\n_Você pode responder com o número ou escrever como prefere seguir._",
  },
  {
    key: "package_action_menu",
    label: "Ações — pacotes",
    category: "fluxo",
    content: "Como deseja seguir?\n\n*1* 📅 Agendar um pacote\n*2* 🔎 Comparar os pacotes\n*3* ↩️ Ver serviços avulsos\n*4* 👤 Falar com um especialista\n\n_Você pode responder com o número ou escrever como prefere seguir._",
  },
  {
    key: "etapa4_vehicle",
    label: "Dados completos do veículo",
    category: "fluxo",
    content: "Para calcular a estimativa e identificar seu veículo automaticamente na chegada, envie os *dados do veículo em uma única mensagem*:\n\n🚗 modelo e ano\n🔠 placa\n🎨 cor\n🔎 estado geral\n\n_Exemplo: Civic 2021, placa BRA2E19, preto, bom estado._\n\nNão precisa seguir um formato exato — pode escrever do seu jeito.",
  },
  {
    key: "etapa4_vehicle_has",
    label: "Veículo já informado",
    category: "fluxo",
    content: "Perfeito. Já localizei os dados do seu veículo no atendimento.\n\nAgora vou preparar a estimativa do serviço.",
  },
  {
    key: "etapa4_ask_year",
    label: "Pedir ano do veículo",
    category: "fluxo",
    hint: "{model}",
    content: "Anotado: *{model}*.\n\nQual é o *ano* do veículo?\n\n_Exemplo: 2021._",
  },
  {
    key: "vehicle_model_not_understood",
    label: "Modelo não entendido",
    category: "fluxo",
    content: "Não consegui identificar o modelo do veículo.\n\nEnvie a marca e o modelo, por exemplo: _Honda Civic_, _Fiat Argo_ ou _Toyota Hilux_.",
  },
  {
    key: "vehicle_year_not_understood",
    label: "Ano não entendido",
    category: "fluxo",
    content: "Preciso do ano com quatro dígitos para seguir.\n\n_Exemplos: 2021, 2019 ou 2015._",
  },
  {
    key: "vehicle_not_understood",
    label: "Veículo não validado",
    category: "fluxo",
    content: "Não consegui identificar todos os dados do veículo nessa mensagem.\n\nEnvie tudo junto, do seu jeito:\n_Exemplo: Civic 2021, placa BRA2E19, preto, bom estado._",
  },
  {
    key: "etapa5_quote",
    label: "Orçamento (etapa 5)",
    category: "fluxo",
    hint: "{name}, {vehicle}, {service}, {valueLine}, {time}, {pitch}",
    content: "*Tudo certo, {name}!*\n\n🚗 {vehicle}\n🛠️ {service}\n{pitch}\n\n{valueLine}  ·  ⏱️ {time}\n\n_Agora escolha o melhor dia no calendário abaixo._",
  },
  {
    key: "etapa6_upsell",
    label: "Recomendação complementar (etapa 6)",
    category: "fluxo",
    hint: "{service}, {complement}, {benefit}",
    content: "*Recomendação técnica*\n\nPara potencializar o resultado de *{service}*, podemos incluir *{complement}* na mesma visita.\n\n*Benefício:* {benefit}\n\n*1* ✅ Incluir {complement}\n*2* ➡️ Seguir apenas com {service}",
  },
  {
    key: "etapa7_day",
    label: "Escolha de dia",
    category: "fluxo",
    content: "📅 Escolha o dia no calendário acima.\n\n_Toque em *Ver dias* ou envie uma data, como *16/08*._",
  },
  {
    key: "etapa7_time",
    label: "Horários disponíveis",
    category: "fluxo",
    hint: "{dayLabel}, {slots}, {durationLabel}",
    content: "*Horários disponíveis — {dayLabel}*\n\nO atendimento dura aproximadamente *{durationLabel}*. Esse período será reservado exclusivamente para o seu veículo.\n\n{slots}\n\n_Responda com o número do horário ou digite, por exemplo, *09:00*._",
  },
  {
    key: "etapa7_no_slots",
    label: "Sem horários no dia",
    category: "fluxo",
    hint: "{dayLabel}",
    content: "Não encontramos uma janela disponível em *{dayLabel}* para a duração deste serviço.\n\nVamos buscar outro dia:",
  },
  {
    key: "etapa8_payment",
    label: "Forma de pagamento",
    category: "fluxo",
    hint: "{options}",
    content: "*Forma de pagamento*\n\nEscolha como prefere pagar:\n\n{options}\n\n_O pagamento é alinhado de forma segura no atendimento._",
  },
  {
    key: "etapa8_payment_compact",
    label: "Forma de pagamento (compacto)",
    category: "fluxo",
    hint: "{options}",
    content: "Escolha a forma de pagamento:\n\n{options}",
  },
  {
    key: "etapa8_pix_block",
    label: "Dados PIX",
    category: "fluxo",
    hint: "{pixKey}, {pixHolder}, {pixBank}, {businessName}",
    content: "*PIX — {businessName}*\n\n🔑 *Chave:* {pixKey}\n👤 *Beneficiário:* {pixHolder}\n{bankLine}\n\n_Confira os dados antes de concluir a transferência._",
  },
  {
    key: "etapa8_pix_choice",
    label: "Escolha de PIX",
    category: "fluxo",
    hint: "",
    content: "*Pagamento via PIX*\n\n*1* PIX agora\n*2* PIX no dia do atendimento\n\n_Responda 1 ou 2, ou escreva *agora* / *no atendimento*._",
  },
  {
    key: "etapa8_receipt_upload",
    label: "Solicitação de comprovante",
    category: "fluxo",
    hint: "{value}",
    content: "Para solicitar a conferência do pagamento, envie uma foto ou print legível do comprovante.\n\n*Valor esperado:* {value}\n\n_A confirmação do pagamento é feita pela equipe antes da reserva ser concluída._",
  },
  {
    key: "etapa8_receipt_invalid",
    label: "Comprovante inválido",
    category: "fluxo",
    hint: "{expected}, {received}",
    content: "Não conseguimos validar o valor deste comprovante.\n\n*Valor esperado:* {expected}\n*Valor identificado:* {received}\n\nEnvie o comprovante correto ou fale com a equipe para receber ajuda.",
  },
  {
    key: "etapa8_receipt_error",
    label: "Erro ao ler comprovante",
    category: "fluxo",
    hint: "",
    content: "Não foi possível ler este comprovante com segurança.\n\nEnvie uma imagem mais nítida, mostrando valor, data e identificação da transação.",
  },
  {
    key: "etapa9_confirm",
    label: "Confirmação final (legado)",
    category: "fluxo",
    hint: "{name}, {vehicle}, {services}, {day}, {time}, {payment}, {value}, {address}, {pixBlock}",
    content: "✅ *Agendamento confirmado*\n\nOlá, *{name}*. Sua reserva foi registrada.\n\n*Dados do atendimento*\n👤 Cliente: {name}\n🚗 Veículo: {vehicle}\n🛠️ Serviço(s): {services}\n📅 Data: {day}\n🕒 Horário: {time}\n💳 Pagamento: {payment}\n💰 Valor estimado: R$ {value}\n\n📍 *Local:* {address}\n{pixBlock}\n\n_Enviaremos um lembrete antes do atendimento. Caso precise ajustar algo, responda por aqui._",
  },
  {
    key: "stale_return",
    label: "Retorno após inatividade",
    category: "fluxo",
    hint: "{name}, {contextLine}, {continueLine}",
    content: "Olá{name}.\n\n{contextLine}\n\n{continueLine}\n\n*1* ✅ Continuar atendimento\n*2* ↩️ Começar novamente",
  },
  {
    key: "indecisive_vehicle",
    label: "Cliente indeciso — veículo",
    category: "fluxo",
    content: "Posso ajudar a encontrar a melhor solução.\n\nQual é o modelo e ano do seu veículo?\n_Exemplo: Civic 2021._",
  },
  {
    key: "indecisive_problem",
    label: "Cliente indeciso — necessidade",
    category: "fluxo",
    content: "Conte com a nossa orientação técnica. Qual situação descreve melhor o seu veículo?\n\n*1* ✨ Pintura opaca, riscada ou sem brilho\n*2* 🧼 Interior sujo, com manchas ou odores\n*3* 🛡️ Quero proteger um carro novo ou recém-adquirido\n*4* 🚗 Quero um cuidado completo\n*5* 💬 Outra necessidade",
  },
  {
    key: "invalid_menu",
    label: "Opção inválida",
    category: "fluxo",
    hint: "{menu}",
    content: "Não identifiquei essa opção. Selecione uma das alternativas abaixo:\n\n{menu}",
  },
  {
    key: "followup_recovery",
    label: "Follow-up por inatividade",
    category: "automacao",
    hint: "{name}",
    content: "Olá{name}. Seu atendimento na Garagem do Ka continua disponível.\n\nQuando quiser, responda a esta mensagem para retomar ou envie *menu* para ver os serviços.",
  },
  {
    key: "reminder_4h",
    label: "Confirmação 2h antes",
    category: "automacao",
    hint: "{brand}, {name}, {service}, {duration}, {dateLabel}, {time}, {addressLine}",
    content: "⏰ *Lembrete de atendimento — {brand}*\n\nOlá, *{name}*. Seu atendimento é hoje:\n\n🛠️ {service} (~{duration})\n📅 {dateLabel}, às *{time}*\n{addressLine}\n\nPara manter a reserva, responda *CONFIRME*.\n_Se precisar ajustar o horário, avise nossa equipe por aqui._",
  },
  {
    key: "reminder_30min",
    label: "Aviso 30min antes",
    category: "automacao",
    hint: "{name}, {service}, {time}",
    content: "🚗 *Seu atendimento está próximo*\n\nOlá, *{name}*. O serviço *{service}* está reservado para *{time}*.\n\nSe houver qualquer imprevisto, responda por aqui para que a equipe possa ajudar.",
  },
  {
    key: "appointment_cancelled",
    label: "Cancelamento automático",
    category: "automacao",
    hint: "{name}, {dateLabel}, {time}, {service}, {reason}",
    content: "Olá, *{name}*.\n\nSeu agendamento foi cancelado:\n\n🛠️ {service}\n📅 {dateLabel}, às {time}\n\n{reason}\n\nPara escolher um novo horário, responda *menu*.",
  },
  {
    key: "appointment_thankyou",
    label: "Agradecimento pós-serviço",
    category: "automacao",
    hint: "{name}, {brand}, {service}",
    content: "✅ *Serviço concluído*\n\nOlá, *{name}*. Finalizamos o serviço *{service}* com todo o cuidado da equipe *{brand}*. Seu veículo está pronto.\n\nComo foi sua experiência? Responda com uma nota de *1 a 5*. Seu retorno nos ajuda a manter um padrão cada vez melhor.\n\nQuando chegar o momento da próxima manutenção estética, lembraremos você por aqui.",
  },
  {
    key: "appointment_checkin",
    label: "Check-in e início do serviço",
    category: "automacao",
    hint: "{name}, {service}, {vehicle}, {brand}",
    content: "🔧 *Serviço iniciado*\n\nOlá, *{name}*. O check-in de *{vehicle}* foi concluído e nossa equipe já iniciou o serviço *{service}*.\n\nVocê pode acompanhar por aqui. Assim que o veículo estiver pronto, a *{brand}* enviará uma nova atualização.",
  },
  {
    key: "appointment_status",
    label: "Consulta de status do veículo",
    category: "automacao",
    hint: "{name}, {service}, {vehicle}, {statusLabel}, {statusMessage}, {dateLabel}, {time}",
    content: "🚘 *Acompanhamento do veículo*\n\nOlá, *{name}*. Localizei o atendimento de *{vehicle}*.\n\n🛠️ *Serviço:* {service}\n📍 *Status:* {statusLabel}\n📅 *Referência:* {dateLabel}, às {time}\n\n{statusMessage}\n\nSe precisar de uma atualização da equipe, responda *9*.",
  },
  {
    key: "category_1",
    label: "Categoria 1 — Lavagem",
    category: "categorias",
    content: "Lavagem & cuidado externo",
  },
  {
    key: "category_2",
    label: "Categoria 2 — Polimento",
    category: "categorias",
    content: "Polimento & correção",
  },
  {
    key: "category_3",
    label: "Categoria 3 — Proteção",
    category: "categorias",
    content: "Proteção de pintura",
  },
  {
    key: "category_4",
    label: "Categoria 4 — Interior",
    category: "categorias",
    content: "Higienização interna",
  },
  {
    key: "category_5",
    label: "Categoria 5 — Detalhes",
    category: "categorias",
    content: "Detalhes especiais",
  },
  {
    key: "category_6",
    label: "Categoria 6 — Revitalização",
    category: "categorias",
    content: "Revitalização",
  },
  {
    key: "category_7",
    label: "Categoria 7 — Pacotes",
    category: "categorias",
    content: "Pacotes premium",
  },
  {
    key: "category_8",
    label: "Categoria 8 — Ajuda",
    category: "categorias",
    content: "Consultoria com IA",
  },
  {
    key: "etapa9_coupon",
    label: "Cupom de desconto",
    category: "fluxo",
    content: "*Você possui cupom de desconto?*\n\n*1* 🎟️ Sim, tenho um cupom\n*2* ➡️ Seguir sem cupom\n\n_Se preferir, já envie o código diretamente._",
  },
  {
    key: "etapa9_loyalty",
    label: "Pontos de fidelidade",
    category: "fluxo",
    hint: "{points}, {discountValue}",
    content: "Você tem *{points} pontos* disponíveis no programa de fidelidade.\n\nEles podem gerar *{discountValue}* de desconto neste atendimento.\n\n*1* ✅ Usar meus pontos\n*2* ➡️ Seguir sem usar",
  },
  {
    key: "etapa10_budget",
    label: "Confirmação de orçamento",
    category: "fluxo",
    hint: "{value}",
    content: "*Resumo financeiro*\n\n💰 *Valor total estimado: {value}*\n\nPodemos avançar para a reserva do horário?\n\n*1* ✅ Confirmar e continuar\n*2* ↩️ Voltar ao menu",
  },
  {
    key: "etapa10_logistics",
    label: "Logística — escolha",
    category: "fluxo",
    content: "*Como o veículo chegará até nós?*\n\n*1* 🚗 Eu levo o veículo até a estética\n*2* 🚚 Solicitar coleta do veículo\n\n_Se escolher coleta, confirmaremos endereço e disponibilidade._",
  },
  {
    key: "etapa10_logistics_client_leads",
    label: "Logística — cliente leva",
    category: "fluxo",
    content: "Perfeito. Reserve o horário e leve seu veículo à Garagem do Ka no dia combinado.\n\nVamos concluir os próximos dados do atendimento.",
  },
  {
    key: "etapa10_logistics_pickup_address",
    label: "Logística — endereço de coleta",
    category: "fluxo",
    content: "Para verificar a coleta, envie o endereço completo onde o veículo estará.\n\n_Informe rua, número, bairro, cidade e complemento, se houver._",
  },
  {
    key: "etapa10_logistics_return_preference",
    label: "Logística — preferência de devolução",
    category: "fluxo",
    content: "Após o serviço, como prefere receber o veículo?\n\n*1* 🚚 Devolver no mesmo endereço\n*2* 🚗 Eu retiro na Garagem do Ka",
  },
  {
    key: "etapa10_logistics_with_return",
    label: "Logística — com devolução",
    category: "fluxo",
    content: "Combinado. A devolução no endereço informado será considerada no resumo do atendimento.",
  },
  {
    key: "etapa10_logistics_without_return",
    label: "Logística — sem devolução",
    category: "fluxo",
    content: "Combinado. A retirada do veículo será feita na Garagem do Ka após a conclusão do serviço.",
  },
  {
    key: "etapa15_summary_confirm",
    label: "Resumo e confirmação",
    category: "fluxo",
    hint: "{name}, {service}, {vehicle}, {day}, {time}, {pickup}, {address}, {payment}, {reminder}, {value}",
    content: "*Resumo do agendamento*\n\n👤 Cliente: {name}\n🛠️ Serviço: {service}\n🚗 Veículo: {vehicle}\n📅 Data: {day}\n🕒 Horário: {time}\n🚚 Coleta: {pickup}\n📍 Endereço: {address}\n💳 Pagamento: {payment}\n🔔 Lembrete: {reminder}\n💰 Valor estimado: {value}\n\n_Cancelamentos sem custo podem ser solicitados com até 2 horas de antecedência._\n\n*1* ✅ Confirmar reserva\n*2* 📅 Alterar data ou horário\n*3* 💳 Alterar forma de pagamento",
  },
  {
    key: "etapa16_confirmation",
    label: "Confirmação final",
    category: "fluxo",
    hint: "{address}, {hours}",
    content: "✅ *Reserva concluída*\n\nSeu atendimento está confirmado.\n\n📍 *Endereço:* {address}\n🕒 *Horário de atendimento:* {hours}\n\nEnviaremos um lembrete antes do horário reservado. Para alterar ou tirar uma dúvida, responda por aqui.",
  },

  // Estados adicionais para substituir mensagens client-facing antes fixas no código.
  {
    key: "first_time_bonus_offer",
    label: "Bônus de primeira compra — oferta",
    category: "fluxo",
    hint: "{discount}",
    content: "🎁 *Benefício de primeira visita*\n\nVocê tem um benefício exclusivo para o seu primeiro serviço.\n\n*Desconto estimado:* {discount}\n\n*1* ✅ Aplicar benefício\n*2* ➡️ Seguir sem desconto",
  },
  {
    key: "first_time_bonus_applied",
    label: "Bônus de primeira compra — aplicado",
    category: "fluxo",
    hint: "{value}",
    content: "✅ Benefício aplicado com sucesso.\n\n*Novo valor estimado:* {value}\n\nVamos continuar com o seu agendamento.",
  },
  {
    key: "first_time_bonus_declined",
    label: "Bônus de primeira compra — recusado",
    category: "fluxo",
    hint: "{value}",
    content: "Sem problemas. Seguiremos com a proposta original.\n\n*Valor estimado:* {value}\n\nVamos continuar com o seu agendamento.",
  },
  {
    key: "reminder_choice",
    label: "Escolha de lembrete",
    category: "fluxo",
    content: "Deseja receber um lembrete pelo WhatsApp antes do atendimento?\n\n*1* 🔔 Sim, quero receber\n*2* ➡️ Não preciso",
  },
  {
    key: "payment_confirmation",
    label: "Pagamento confirmado",
    category: "fluxo",
    hint: "{receiptAmount}, {totalPaid}",
    content: "✅ *Pagamento confirmado*\n\n*Valor do comprovante:* {receiptAmount}\n*Total pago:* {totalPaid}\n\nSeu pagamento foi registrado. Agora confirme o resumo para concluir sua reserva.",
  },
  {
    key: "handoff_ack",
    label: "Transferência para atendimento humano",
    category: "fluxo",
    hint: "{name}",
    content: "Perfeito{name}.\n\nSeu atendimento foi encaminhado para um especialista da Garagem do Ka. A assistente virtual ficará em pausa para que a equipe assuma a conversa por aqui.",
  },
  {
    key: "ai_followup",
    label: "Próximo passo após resposta da IA",
    category: "fluxo",
    content: "Posso ajudar em mais alguma etapa?\n\n*1* ↩️ Voltar para o atendimento\n*2* 🧭 Ver o menu principal\n*3* 👤 Falar com um especialista",
  },
  {
    key: "slot_unavailable",
    label: "Horário indisponível",
    category: "fluxo",
    hint: "{slots}",
    content: "Esse horário acabou de ser reservado por outro cliente.\n\nPara manter sua experiência ágil, escolha uma das opções ainda disponíveis:\n\n{slots}",
  },
  {
    key: "vehicle_confirmation",
    label: "Confirmação dos dados do veículo",
    category: "fluxo",
    hint: "{model}, {year}, {plate}, {color}, {condition}",
    content: "*Só para confirmar o veículo*\n\n🚗 {model} — {year}\n🔠 Placa: *{plate}*\n🎨 {color}\n🔎 {condition}\n\n*1* ✅ Está correto, ver estimativa\n*2* ✏️ Quero corrigir\n\n_Se preferir, já escreva a correção. Ex.: “a placa é BRA2E19”._",
  },
  {
    key: "vehicle_missing_details",
    label: "Dados que faltam do veículo",
    category: "fluxo",
    hint: "{known}, {missing}, {example}",
    content: "Entendi até aqui: *{known}*.\n\nPara concluir, envie em uma única mensagem: *{missing}*.\n_Exemplo: {example}._",
  },
  {
    key: "vehicle_color_request",
    label: "Pedir cor do veículo",
    category: "fluxo",
    hint: "{vehicle}",
    content: "Anotado: *{vehicle}*.\n\nQual é a cor predominante do veículo?",
  },
  {
    key: "vehicle_condition_request",
    label: "Pedir estado do veículo",
    category: "fluxo",
    hint: "{vehicle}",
    content: "Perfeito. Para refinar a estimativa de *{vehicle}*, como está o estado geral?\n\n_Exemplos: excelente, bom, normal ou precisa de atenção._",
  },
  {
    key: "vehicle_color_invalid",
    label: "Cor do veículo não entendida",
    category: "fluxo",
    content: "Não consegui identificar a cor. Informe novamente, por exemplo: *branco*, *prata*, *preto* ou *azul*.",
  },
  {
    key: "upsell_offer",
    label: "Oferta de serviço complementar",
    category: "fluxo",
    hint: "{complement}, {value}",
    content: "*Sugestão para a mesma visita*\n\nAdicionar *{complement}* agora custa *{value}* a mais e permite finalizar o veículo em uma única entrega.\n\n*1* ✅ Incluir\n*2* ➡️ Seguir sem incluir",
  },
  {
    key: "upsell_added",
    label: "Serviço complementar incluído",
    category: "fluxo",
    hint: "{complement}",
    content: "✅ *{complement}* foi incluído no seu atendimento.\n\nAgora vamos escolher a melhor data para a reserva.",
  },
  {
    key: "coupon_code_request",
    label: "Solicitação de código de cupom",
    category: "fluxo",
    content: "Perfeito. Envie o *código do cupom* exatamente como recebeu.\n\n_Exemplo: BEMVINDO10._",
  },
  {
    key: "coupon_applied",
    label: "Cupom aplicado",
    category: "fluxo",
    hint: "{code}, {discount}, {value}",
    content: "✅ *Cupom {code} aplicado*\n\n💸 Desconto: {discount}\n💰 Novo valor estimado: {value}\n\nAgora vamos verificar seus pontos de fidelidade antes de escolher o pagamento.",
  },
  {
    key: "summary_review",
    label: "Revisão do resumo",
    category: "fluxo",
    content: "Confira o resumo do agendamento acima.\n\n*1* ✅ Confirmar reserva\n*2* ✏️ Alterar data ou horário\n*3* 💳 Alterar forma de pagamento",
  },
  {
    key: "evaluation_required",
    label: "Avaliação técnica necessária",
    category: "fluxo",
    content: "🔎 *Avaliação técnica necessária*\n\nPara este serviço, precisamos avaliar o veículo antes de informar valor e reservar o atendimento. Vou encaminhar sua conversa para um especialista.",
  },
];
