/** Catálogo Garagem do Ka — serviços, preços e categorias */

export const BRAND_DEFAULT = "Garagem do Ka";

export interface CatalogItem {
  key: string;
  label: string;
  short: string;
  pitch: string;
  dbMatch: string;
  time: string;
  hatchMin: number;
  hatchMax: number;
  suvMin: number;
  suvMax: number;
}

export const CATEGORIES: Record<number, { title: string; keys: string[] }> = {
  1: { title: "Lavagem", keys: ["lavagem_tecnica", "lavagem_detalhada"] },
  2: { title: "Polimento", keys: ["polimento_comercial", "polimento_tecnico"] },
  3: {
    title: "Proteção & Brilho",
    keys: ["vitrificacao", "protecao_ceramica", "cristalizacao", "espelhamento"],
  },
  4: { title: "Interior", keys: ["higienizacao_interna", "hidratacao_couro"] },
  5: {
    title: "Revitalização",
    keys: ["revitalizacao_pintura", "descontaminacao", "limpeza_premium"],
  },
  6: {
    title: "Detalhes Especiais",
    keys: ["limpeza_motor", "restauracao_farois", "chuva_acida"],
  },
  7: { title: "Pacotes Premium", keys: ["pacotes"] },
  8: { title: "Ajuda na escolha", keys: ["indeciso"] },
};

export const CATALOG: Record<string, CatalogItem> = {
  lavagem_tecnica: {
    key: "lavagem_tecnica",
    label: "Lavagem Técnica",
    short: "Lavagem técnica com produtos premium e acabamento cuidadoso.",
    pitch: "Ideal para manutenção frequente com proteção da pintura.",
    dbMatch: "Lavagem",
    time: "1h a 2h",
    hatchMin: 70,
    hatchMax: 110,
    suvMin: 110,
    suvMax: 140,
  },
  lavagem_detalhada: {
    key: "lavagem_detalhada",
    label: "Lavagem Detalhada",
    short: "Limpeza completa interna e externa com atenção aos detalhes.",
    pitch: "Seu carro com aspecto de recém-saído do estúdio.",
    dbMatch: "Lavagem",
    time: "1h30 a 2h30",
    hatchMin: 90,
    hatchMax: 140,
    suvMin: 130,
    suvMax: 170,
  },
  polimento_comercial: {
    key: "polimento_comercial",
    label: "Polimento Comercial",
    short: "Realce de brilho e melhora visual rápida da pintura.",
    pitch: "Ótimo para eventos ou revitalização leve.",
    dbMatch: "Polimento",
    time: "2h a 4h",
    hatchMin: 250,
    hatchMax: 380,
    suvMin: 380,
    suvMax: 520,
  },
  polimento_tecnico: {
    key: "polimento_tecnico",
    label: "Polimento Técnico",
    short: "Correção de micro riscos, marcas e opacidade com brilho profundo.",
    pitch: "Recupera o brilho e o aspecto premium da pintura.",
    dbMatch: "Polimento",
    time: "3h a 6h",
    hatchMin: 380,
    hatchMax: 580,
    suvMin: 580,
    suvMax: 850,
  },
  vitrificacao: {
    key: "vitrificacao",
    label: "Vitrificação",
    short: "Proteção de alta durabilidade com brilho intenso.",
    pitch: "Protege contra UV, chuva ácida e facilita a limpeza.",
    dbMatch: "Vitrificação",
    time: "3h a 5h",
    hatchMin: 750,
    hatchMax: 1100,
    suvMin: 1100,
    suvMax: 1700,
  },
  protecao_ceramica: {
    key: "protecao_ceramica",
    label: "Proteção Cerâmica",
    short: "Camada cerâmica premium para máxima proteção.",
    pitch: "Durabilidade superior e brilho de vitrine.",
    dbMatch: "Vitrificação",
    time: "4h a 6h",
    hatchMin: 900,
    hatchMax: 1300,
    suvMin: 1300,
    suvMax: 1900,
  },
  cristalizacao: {
    key: "cristalizacao",
    label: "Cristalização",
    short: "Sela a pintura com brilho profundo e proteção intermediária.",
    pitch: "Excelente custo-benefício em brilho e proteção.",
    dbMatch: "Cristalização",
    time: "2h a 4h",
    hatchMin: 300,
    hatchMax: 450,
    suvMin: 420,
    suvMax: 620,
  },
  espelhamento: {
    key: "espelhamento",
    label: "Espelhamento",
    short: "Acabamento espelhado com alto nível de reflexo.",
    pitch: "Visual impactante e acabamento de vitrine.",
    dbMatch: "Polimento",
    time: "3h a 5h",
    hatchMin: 450,
    hatchMax: 650,
    suvMin: 650,
    suvMax: 900,
  },
  higienizacao_interna: {
    key: "higienizacao_interna",
    label: "Higienização Interna",
    short: "Limpeza profunda de estofados, carpetes e ar-condicionado.",
    pitch: "Elimina odores, ácaros e sujeira acumulada.",
    dbMatch: "Higienização",
    time: "3h a 5h",
    hatchMin: 220,
    hatchMax: 320,
    suvMin: 320,
    suvMax: 480,
  },
  hidratacao_couro: {
    key: "hidratacao_couro",
    label: "Hidratação de Couro",
    short: "Limpeza e nutrição dos bancos em couro.",
    pitch: "Recupera maciez e aparência premium do interior.",
    dbMatch: "Higienização",
    time: "1h30 a 3h",
    hatchMin: 180,
    hatchMax: 280,
    suvMin: 260,
    suvMax: 380,
  },
  revitalizacao_pintura: {
    key: "revitalizacao_pintura",
    label: "Revitalização de Pintura",
    short: "Recuperação estética completa da pintura.",
    pitch: "Para pinturas opacas, sem vida ou muito desgastadas.",
    dbMatch: "Polimento",
    time: "4h a 8h",
    hatchMin: 500,
    hatchMax: 800,
    suvMin: 750,
    suvMax: 1100,
  },
  descontaminacao: {
    key: "descontaminacao",
    label: "Descontaminação de Pintura",
    short: "Remove contaminantes antes de polir ou proteger.",
    pitch: "Prepara a pintura para resultado perfeito.",
    dbMatch: "Polimento",
    time: "1h30 a 3h",
    hatchMin: 200,
    hatchMax: 320,
    suvMin: 280,
    suvMax: 420,
  },
  limpeza_premium: {
    key: "limpeza_premium",
    label: "Limpeza Premium",
    short: "Detalhamento completo de acabamento externo.",
    pitch: "Acabamento impecável em cada detalhe.",
    dbMatch: "Lavagem",
    time: "2h a 4h",
    hatchMin: 150,
    hatchMax: 250,
    suvMin: 220,
    suvMax: 340,
  },
  limpeza_motor: {
    key: "limpeza_motor",
    label: "Limpeza de Motor",
    short: "Limpeza técnica e segura do compartimento.",
    pitch: "Visual impecável para venda ou manutenção premium.",
    dbMatch: "Limpeza de motor",
    time: "1h30 a 2h30",
    hatchMin: 180,
    hatchMax: 260,
    suvMin: 220,
    suvMax: 320,
  },
  restauracao_farois: {
    key: "restauracao_farois",
    label: "Restauração de Faróis",
    short: "Recupera transparência e aparência dos faróis.",
    pitch: "Melhora estética e visibilidade noturna.",
    dbMatch: "Detalhamento",
    time: "1h a 2h",
    hatchMin: 120,
    hatchMax: 200,
    suvMin: 150,
    suvMax: 240,
  },
  chuva_acida: {
    key: "chuva_acida",
    label: "Remoção de Chuva Ácida",
    short: "Elimina manchas de chuva ácida em vidros e pintura.",
    pitch: "Recupera clareza e acabamento.",
    dbMatch: "Detalhamento",
    time: "1h a 3h",
    hatchMin: 150,
    hatchMax: 280,
    suvMin: 200,
    suvMax: 350,
  },
  pacotes: {
    key: "pacotes",
    label: "Pacotes Premium",
    short: "Combos com melhor custo-benefício.",
    pitch: "Proteção, brilho e detalhamento combinados.",
    dbMatch: "Detalhamento",
    time: "1 dia",
    hatchMin: 550,
    hatchMax: 900,
    suvMin: 900,
    suvMax: 1500,
  },
  indeciso: {
    key: "indeciso",
    label: "Consultoria",
    short: "Te ajudo a escolher o melhor serviço.",
    pitch: "",
    dbMatch: "Lavagem",
    time: "—",
    hatchMin: 0,
    hatchMax: 0,
    suvMin: 0,
    suvMax: 0,
  },
};

export const UPSELL_BY_KEY: Record<string, { complement: string; benefit: string }> = {
  lavagem_detalhada: {
    complement: "Higienização Interna",
    benefit: "deixa o carro perfeito por dentro e por fora no mesmo dia.",
  },
  polimento_tecnico: {
    complement: "Vitrificação",
    benefit: "protege o brilho do polimento por muito mais tempo.",
  },
  polimento_comercial: {
    complement: "Cristalização",
    benefit: "aumenta durabilidade do brilho obtido.",
  },
  vitrificacao: {
    complement: "Descontaminação",
    benefit: "prepara a pintura e potencializa a proteção.",
  },
  higienizacao_interna: {
    complement: "Hidratação de Couro",
    benefit: "finaliza o interior com acabamento premium.",
  },
  cristalizacao: {
    complement: "Polimento Técnico",
    benefit: "maximiza o resultado da proteção.",
  },
};

export const UNDECIDED_TO_KEY: Record<number, string> = {
  1: "polimento_tecnico",
  2: "higienizacao_interna",
  3: "vitrificacao",
  4: "pacotes",
  5: "lavagem_detalhada",
};
