import { useState, useEffect, useMemo, useRef, useCallback } from 'react';
import { invokeWithQueue } from '@/lib/invokeQueue';
import type { ImagesMap } from './useDiagnosisImages';
import { getStaticDiagnosticImage, setStaticDiagnosticImage } from '@/lib/diagnosticImageLoader';
import { useSectionImagesContext } from '@/contexts/SectionImagesContext';
import { OCCASION_EN, SEASON_PALETTE, STYLE_EN, STYLE_PALETTE } from '@/lib/imageTranslations';
import { normalizeToken } from '@/lib/pieceKey';
import { buildPieceQuery, buildPieceQueryLadder } from '@/lib/pieceFragments';
import { buildAutoGeneratedImagePrompt, buildFastPollinationsUrl } from '@/lib/imageService';
// REFATORAÇÃO: perfil único de imagem por diagnóstico — ver
// imageDiagnosisProfile.ts para o racional completo. Este é o ÚNICO
// lugar que deve derivar cor/tecido/paleta a partir do diagnóstico;
// tudo o mais (pieceFragments, ladder EN) recebe o resultado pronto.
import { getDiagnosisImageProfile, type DiagnosisImageProfile } from '@/lib/imageDiagnosisProfile';

const fetchInFlight = new Map<string, Promise<string | null>>();
const PROVIDER_FALLBACK_TIMEOUT_MS = 2200;
// Versão do pipeline bump — muda a chave de cache para que diagnósticos
// antigos (gerados com queries inconsistentes/aleatórias) NÃO reaproveitem
// imagens erradas do cache; forçamos nova busca com a lógica corrigida.
const IMAGE_SEARCH_PIPELINE_VERSION = 'v23_no_pexels';

type ProviderMode = 'default' | 'duckduckgoOnly' | 'pexelsOnly';
const PRIMARY_PROVIDER = 'pexels-search-image' as const;
const IMAGE_PROVIDERS = ['duckduckgo-search-image', 'unsplash-search-image', 'openverse-search-image', 'pixabay-search-image'] as const;
const REAL_PROVIDERS = [PRIMARY_PROVIDER, ...IMAGE_PROVIDERS] as const;
type ProviderFn = typeof REAL_PROVIDERS[number];

const PROVIDER_ORDER_BY_MODE: Record<ProviderMode, ProviderFn[]> = {
  default: [PRIMARY_PROVIDER, 'duckduckgo-search-image', 'pixabay-search-image', 'unsplash-search-image'],
  duckduckgoOnly: ['duckduckgo-search-image'],
  pexelsOnly: [PRIMARY_PROVIDER],
};

export function getProviderOrder(seed: number, mode: ProviderMode = 'default'): ProviderFn[] {
  const imageProviders = PROVIDER_ORDER_BY_MODE[mode];
  if (mode === 'default') {
    const rest = imageProviders.slice(1);
    const offset = rest.length ? seed % rest.length : 0;
    return [imageProviders[0], ...rest.slice(offset), ...rest.slice(0, offset)] as ProviderFn[];
  }
  const offset = seed % imageProviders.length;
  const rotated = [...imageProviders.slice(offset), ...imageProviders.slice(0, offset)];
  return rotated as ProviderFn[];
}

function providerRotation(seed: number, mode: ProviderMode = 'default'): ProviderFn[] {
  return getProviderOrder(seed, mode);
}

export function buildSearchQueryForContext(query: string, strictProductShot?: boolean): string {
  const base = (query || '').replace(/\s+/g, ' ').trim();
  if (!strictProductShot || !base) return base;
  return `${base} isolated garment product shot white background no person`.slice(0, 120).trim();
}

function hashString(value: string): number {
  let h = 2166136261;
  for (let i = 0; i < value.length; i += 1) {
    h ^= value.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function isLocalFallbackImage(_imageUrl: string | null | undefined): boolean {
  return false;
}

export function extractProviderImageResult(result: { data?: any; error?: any }) {
  const body = result?.data ?? null;
  const payloadImageUrl = typeof body?.imageUrl === 'string' && body.imageUrl.trim()
    ? body.imageUrl.trim()
    : null;
  const payloadProviderStatus = body?.providerStatus ?? body?.status ?? null;
  const hasSuccessfulPayload = Boolean(body && payloadImageUrl && (payloadProviderStatus === 200 || payloadProviderStatus === '200' || payloadProviderStatus === null));
  const sdkErrorMessage = String(result?.error?.message || result?.error || '');
  const hasSdkErrorWrapper = Boolean(result?.error) && !payloadImageUrl;

  const imageUrl = payloadImageUrl || null;
  const providerStatus = payloadProviderStatus ?? (hasSuccessfulPayload ? 200 : null);
  const providerMessage = String(body?.providerError || body?.error || body?.message || sdkErrorMessage || '');
  const shouldTreatAsSuccess = Boolean(imageUrl && (hasSuccessfulPayload || (!hasSdkErrorWrapper && !sdkErrorMessage)));

  return {
    imageUrl,
    providerStatus,
    providerMessage,
    shouldTreatAsSuccess,
    hasSdkErrorWrapper,
  };
}

export function isTrustedImageUrl(imageUrl: string | null | undefined, provider: string | null | undefined): boolean {
  if (!imageUrl) return false;
  const normalized = imageUrl.toLowerCase();
  if (provider === 'unsplash-search-image') {
    return normalized.includes('images.unsplash.com') || normalized.includes('unsplash.com');
  }
  if (provider === 'pexels-search-image') {
    return normalized.includes('images.pexels.com') || normalized.includes('pexels.com');
  }
  if (provider === 'pixabay-search-image') {
    return normalized.includes('pixabay.com') || normalized.includes('cdn.pixabay.com');
  }
  if (provider === 'openverse-search-image') {
    return normalized.includes('openverse') || normalized.includes('creativecommons');
  }
  return false;
}

// ---------------------------------------------------------------------
// Tradução literal PT→EN de tokens de peça (mantida do arquivo original —
// necessária para o ladder legado que ainda alimenta Pexels/Unsplash/
// Pixabay, que indexam majoritariamente em inglês).
// ---------------------------------------------------------------------
const TOKEN_EN: Record<string, string> = {
  moletom: 'sweatshirt', moleton: 'sweatshirt', hoodie: 'hoodie',
  blusa: 'blouse', camisa: 'shirt', camiseta: 't-shirt', regata: 'tank top',
  body: 'bodysuit', polo: 'polo shirt', tricot: 'knit sweater',
  sueter: 'sweater', cardiga: 'cardigan', cardigan: 'cardigan',
  colete: 'vest', kimono: 'kimono',
  vestido: 'dress', macacao: 'jumpsuit', macaquinho: 'romper',
  calca: 'trousers', jeans: 'jeans', legging: 'leggings',
  saia: 'skirt', short: 'shorts', shorts: 'shorts', bermuda: 'bermuda shorts',
  blazer: 'blazer', jaqueta: 'jacket', casaco: 'coat',
  trench: 'trench coat', sobretudo: 'overcoat', parka: 'parka',
  mocassim: 'loafers', loafer: 'loafers', scarpin: 'pumps',
  mule: 'mule shoes', sandalia: 'sandals', tenis: 'sneakers',
  bota: 'boots', coturno: 'combat boots', papete: 'sport sandals',
  rasteirinha: 'flat sandals', sapatilha: 'flats', oxford: 'oxford shoes',
  slingback: 'slingback', sapato: 'shoes',
  bolsa: 'handbag', clutch: 'clutch', mochila: 'backpack',
  pochete: 'belt bag', carteira: 'wallet',
  chapeu: 'hat', boina: 'beret', lenco: 'scarf',
  cinto: 'belt', oculos: 'sunglasses',
  longo: 'long', longa: 'long', curto: 'short', curta: 'short',
  midi: 'midi', mini: 'mini', maxi: 'maxi', cropped: 'cropped',
  oversized: 'oversized', slim: 'slim', skinny: 'skinny',
  reta: 'straight', reto: 'straight', pantalona: 'wide-leg',
  flare: 'flare', wide: 'wide', cargo: 'cargo', jogger: 'jogger',
  alfaiataria: 'tailored', evase: 'a-line', gode: 'flared',
  plissada: 'pleated', plissado: 'pleated', lapis: 'pencil',
  mom: 'mom', boyfriend: 'boyfriend',
  estruturada: 'structured', estruturado: 'structured',
  fluida: 'flowy', fluido: 'flowy',
  alta: 'high-waisted', alto: 'high-waisted',
  baixa: 'low-rise', baixo: 'low-rise', cintura: 'waist',
  decote: 'v-neck', canoa: 'boat neck',
  nadador: 'racerback', nadadora: 'racerback', ombro: 'shoulder',
  algodao: 'cotton', linho: 'linen', seda: 'silk', couro: 'leather',
  jean: 'denim', denim: 'denim', malha: 'knit', la: 'wool',
  veludo: 'velvet', renda: 'lace', tule: 'tulle', cetim: 'satin',
  viscose: 'viscose', poliester: 'polyester', tricoline: 'cotton shirt',
};

const PROBLEM_STOPWORDS = new Set([
  'pala', 'poncho', 'gaucho', 'nordestino', 'nordestina', 'sertao', 'sertaneja',
  'caipira', 'tipico', 'tipica', 'folclorico', 'folclorica', 'regional', 'tradicional',
  'com', 'de', 'da', 'do', 'em', 'para', 'estilo', 'tipo',
]);

function stripAccents(s: string): string {
  return s.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

function cleanPieceNamePT(pieceName: string): string {
  const lower = stripAccents(pieceName.toLowerCase());
  const tokens = lower.split(/[^a-z0-9-]+/).filter(Boolean);
  const kept = tokens.filter((t) => !PROBLEM_STOPWORDS.has(t));
  return kept.join(' ').trim();
}

function translateLiteralEN(literalPT: string): string {
  const tokens = literalPT.split(/\s+/).filter(Boolean);
  const out: string[] = [];
  const seen = new Set<string>();
  for (const t of tokens) {
    const en = TOKEN_EN[t] || t;
    for (const w of en.split(/\s+/)) {
      const key = w.toLowerCase();
      if (!seen.has(key)) { seen.add(key); out.push(w); }
    }
  }
  return out.join(' ').trim();
}

const CATEGORY_ANCHOR_EN: Record<string, string> = {
  tops: 'blouse woman', bottoms: 'trousers woman', vestidos: 'dress woman',
  tercas_pecas: 'blazer woman', calcados: 'shoes woman fashion', bolsas: 'handbag woman fashion',
};

/**
 * Query EN de fallback: literal traduzido + cor/tecido do PERFIL ÚNICO
 * (não mais extraído ad-hoc do nome da peça) + âncora "woman" SEMPRE.
 * Isso é o que corrige a inconsistência: se a peça não menciona cor,
 * antes a query saía sem cor; agora usa a cor âncora do diagnóstico.
 */
function buildQueryEN(pieceName: string, categoryKey: string | undefined, profile: DiagnosisImageProfile): string {
  const literalPT = cleanPieceNamePT(pieceName);
  const literalEN = translateLiteralEN(literalPT);
  const anchor = CATEGORY_ANCHOR_EN[categoryKey || ''] || 'woman fashion';
  const colorToken = /\b(navy|blue|black|white|grey|beige|brown|red|green|pink|violet|yellow|orange)\b/i
    .test(literalEN) ? '' : ` ${profile.colorEN}`;
  if (literalEN) return `${literalEN}${colorToken} ${anchor}`.replace(/\s+/g, ' ').trim();
  return `${profile.colorEN} ${anchor}`;
}

function uniqueQueries(values: Array<string | null | undefined>): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of values) {
    const q = (raw || '').replace(/\s+/g, ' ').trim();
    if (!q) continue;
    const key = q.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(q);
  }
  return out;
}

/**
 * Ladder EN de fallback (Pexels/Unsplash/Pixabay). Encurta 1 token por
 * vez a partir do literal traduzido, sempre preservando a âncora
 * "woman"/categoria — nunca deixa uma query neutra em gênero passar
 * para um provedor que pode devolver foto masculina.
 */
function buildProgressiveFallbackQueries(
  primaryQuery: string,
  pieceName: string,
  categoryKey: string | undefined,
  profile: DiagnosisImageProfile,
): string[] {
  const literalPT = cleanPieceNamePT(pieceName);
  const literalEN = translateLiteralEN(literalPT);
  const literalTokensEN = literalEN.split(/\s+/).filter(Boolean);
  const anchor = CATEGORY_ANCHOR_EN[categoryKey || ''] || 'woman fashion';

  const ladder: Array<string | null> = [primaryQuery, `${literalEN} ${anchor}`.trim(), literalEN];
  for (let n = literalTokensEN.length - 1; n >= 1; n -= 1) {
    ladder.push(literalTokensEN.slice(0, n).join(' '));
  }
  ladder.push(`${profile.colorEN} ${anchor}`);
  ladder.push(anchor);
  return uniqueQueries(ladder).map((q) => q.split(/\s+/).slice(0, 6).join(' ').slice(0, 80));
}

const providerCooldownUntil = new Map<string, number>();
const PROVIDER_COOLDOWN_MS = 60_000;

interface ImageSearchContext {
  colorHint?: string;
  styleHint?: string;
  paletteHint?: string;
  occasionHint?: string;
  excludeUrls?: string[];
  strictProductShot?: boolean;
  categoryKey?: string;
  providerMode?: ProviderMode;
  /** Perfil único normalizado — sempre presente após a refatoração. */
  profile: DiagnosisImageProfile;
}

interface BrokerFallbackOptions {
  diagnosisId?: string;
  mode?: 'product' | 'editorial';
  category?: string;
  section?: string;
  metadata?: Record<string, unknown>;
  exclusions?: string[];
  require?: string[][];
  forbid?: string[];
  color?: string;
  providerMode?: ProviderMode;
  strictProductShot?: boolean;
}

function isBlacklistedImageUrl(imageUrl: string, providerMsg: string, providerFn?: string) {
  try {
    const url = new URL(imageUrl);
    const host = (url.hostname || '').toLowerCase();
    const path = (url.pathname || '').toLowerCase();
    const search = (url.search || '').toLowerCase();

    const domainBlacklist = ['shutterstock', 'gettyimages', 'getty', 'istockphoto', 'depositphotos', 'adobe', '123rf', 'dreamstime', 'alibaba', 'aliexpress'];
    for (const d of domainBlacklist) if (host.includes(d)) return `blacklisted_domain:${d}`;

    const packagingKeywords = ['perfume', 'parfum', 'bottle', 'packaging', 'box', 'label', 'carton', 'catalogo', 'catalog', 'cover', 'poster', 'banner', 'ad', 'advert', 'promo', 'pack', 'logo', 'brand', 'watermark'];

    // Objects / scenes we explicitly never want as section thumbnails
    const nonClothingObjects = ['tomato', 'vegetable', 'vegetables', 'fruit', 'fruta', 'frutas', 'hay', 'straw', 'bale', 'hay bale', 'straw bale', 'agriculture', 'farm', 'orchard', 'barn'];
    for (const k of nonClothingObjects) if (path.includes(k) || search.includes(k) || providerMsg.toLowerCase().includes(k)) return `non_clothing_object:${k}`;

    // Reject obvious social/video platform hosts or provider messages that indicate video
    const videoHosts = ['youtube.com', 'youtu.be', 'vimeo.com', 'tiktok.com', 'instagram.com', 'facebook.com', 'pinterest.com'];
    for (const vh of videoHosts) if (host.includes(vh)) return `video_host:${vh}`;
    if (/video|youtube|tiktok|vimeo|instagram|facebook|pinterest/.test(providerMsg.toLowerCase())) return 'provider_indicated_video';
    for (const k of packagingKeywords) if (path.includes(k) || search.includes(k) || providerMsg.toLowerCase().includes(k)) return `packaging_or_promo:${k}`;

    if (path.endsWith('.svg') || path.includes('typography') || path.includes('wordart') || path.includes('calligraphy')) return 'text_art';

    // Additional filename/path heuristics: many bad results are delivered
    // as thumbnails, covers, or video frames whose filename contains
    // words like "thumb", "thumbnail", "screenshot", "frame" or
    // resolution markers like "720p". Reject these proactively.
    const filename = (path.split('/').pop() || '').toLowerCase();
    const extMatch = filename.match(/\.([a-z0-9]+)$/);
    const ext = extMatch ? extMatch[1] : '';
    const videoExtensions = new Set(['mp4', 'webm', 'mov', 'mkv', 'flv', 'avi']);
    if (videoExtensions.has(ext)) return `video_extension:${ext}`;

    const thumbnailIndicators = ['thumb', 'thumbnail', 'screenshot', 'screen', 'still', 'frame', 'preview', 'poster', 'cover', 'crop', 'social'];
    for (const ind of thumbnailIndicators) if (filename.includes(ind)) return `thumbnail_indicator:${ind}`;

    // reject resolution markers (e.g. 720p, 1080p) and typical video-ish tokens
    if (/\b\d{3,4}p\b/.test(filename) || /(?:video|clip|trailer|screenrecord)/.test(filename)) return 'video_like_filename';

    // Reject filenames that are numeric frames or huge numeric sequences
    if (/frame[_-]?\d{2,}|^\d{6,}$/.test(filename)) return 'frame_sequence';

    return false;
  } catch {
    return false;
  }
}

export async function searchRealProvidersFallback(
  queries: string[],
  originalQuery: string,
  excludeUrls?: Set<string> | Iterable<string> | null,
  seed?: number,
  brokerOptions?: BrokerFallbackOptions,
): Promise<string | null> {
  const exclude = excludeUrls instanceof Set
    ? excludeUrls
    : new Set<string>(excludeUrls ? Array.from(excludeUrls) : []);
  const baseSeed = typeof seed === 'number' && Number.isFinite(seed) ? seed >>> 0 : hashString(originalQuery);
  const exclusions = Array.from(new Set([
    ...(Array.isArray(brokerOptions?.exclusions) ? brokerOptions!.exclusions! : []),
    ...(Array.isArray(brokerOptions?.forbid) ? brokerOptions!.forbid! : []),
  ])).slice(0, 40);
  const pageHint = ((baseSeed >>> 3) % 5) + 1;
  const candidateQueries = brokerOptions?.strictProductShot ? queries.slice(0, 2) : queries;
  let qIdx = 0;
  for (const fallbackQuery of candidateQueries) {
    let pIdx = 0;
    const providers = providerRotation(baseSeed, brokerOptions?.providerMode ?? 'default');
    const fastProviders = brokerOptions?.strictProductShot
      ? [PRIMARY_PROVIDER, ...providers.filter((provider) => provider !== PRIMARY_PROVIDER)]
      : providers;
    for (const providerFn of fastProviders) {
      const cooldown = providerCooldownUntil.get(providerFn) || 0;
      if (Date.now() < cooldown) { pIdx += 1; continue; }
      const providerSeed = (baseSeed + qIdx * 131 + pIdx * 977) >>> 0;
      try {
        const effectiveQuery = buildSearchQueryForContext(fallbackQuery, brokerOptions?.strictProductShot);
        const timeoutMs = providerFn === PRIMARY_PROVIDER ? 1600 : providerFn === 'duckduckgo-search-image' ? 1800 : 2200;
        const result = await invokeWithQueue(providerFn, {
          body: {
            query: (effectiveQuery.length > 120
              ? effectiveQuery.slice(0, 120).replace(/\s+\S*$/, '').trim()
              : effectiveQuery),
            exclude_urls: Array.from(exclude).slice(-120),
            exclude_terms: exclusions,
            seed: providerSeed,
            page: pageHint,
            // CORREÇÃO: `mode` agora é de fato propagado no body. Antes era
            // montado em brokerOptions e nunca chegava na edge function.
            // NOTA: a edge function duckduckgo-search-image atual ainda NÃO
            // lê este campo (ver refatoração dela em anexo) — mantenha os
            // dois arquivos sincronizados se algum outro provider passar a
            // usar `mode` no futuro.
            ...(brokerOptions?.mode ? { mode: brokerOptions.mode } : {}),
            ...(brokerOptions?.color ? { color: brokerOptions.color } : {}),
            ...(brokerOptions?.require?.length ? { require: brokerOptions.require } : {}),
          },
        }, { timeoutMs, retries: 0 });

        const parsed = extractProviderImageResult(result as { data?: any; error?: any });
        const providerStatus = parsed.providerStatus;
        const providerMessage = parsed.providerMessage;
        if (providerStatus === 429 || providerStatus === '429' || result.data?.skipped || /429|Too Many Requests|Throttle/i.test(providerMessage)) {
          if (providerFn !== 'pexels-search-image') {
            providerCooldownUntil.set(providerFn, Date.now() + PROVIDER_COOLDOWN_MS);
          }
          pIdx += 1;
          continue;
        }

        const imageUrl = parsed.imageUrl;
        if (parsed.shouldTreatAsSuccess && imageUrl && !exclude.has(imageUrl)) {
          const rejectReason = isBlacklistedImageUrl(imageUrl, providerMessage, providerFn as string);
          if (rejectReason) {
            console.log('[image-search:fallback] rejected image by url blacklist', { imageUrl, provider: providerFn, reason: rejectReason });
            pIdx += 1;
            continue;
          }
          if (!isTrustedImageUrl(imageUrl, providerFn)) {
            console.log('[image-search:fallback] rejected image by provider trust validation', { imageUrl, provider: providerFn });
            pIdx += 1;
            continue;
          }
          console.log('[image-search:fallback]', providerFn, 'ok', { query: fallbackQuery, original: originalQuery, seed: providerSeed });
          return imageUrl;
        }
        if (imageUrl && exclude.has(imageUrl)) { pIdx += 1; continue; }
        const errMsg = parsed.providerMessage;
        if (/429|Too Many Requests|Throttle/i.test(errMsg)) {
          if (providerFn !== 'pexels-search-image') {
            providerCooldownUntil.set(providerFn, Date.now() + PROVIDER_COOLDOWN_MS);
          }
        }
      } catch (err: any) {
        const msg = String(err?.message || err || '');
        if (/429|Throttle|Too Many/i.test(msg) && providerFn !== 'pexels-search-image') {
          providerCooldownUntil.set(providerFn, Date.now() + PROVIDER_COOLDOWN_MS);
        }
      }
      pIdx += 1;
    }
    qIdx += 1;
  }
  return null;
}

async function searchInternetImage(
  pieceName: string,
  diagnosisId: string,
  category: string | undefined,
  seed: number | undefined,
  searchContext: ImageSearchContext,
): Promise<string | null> {
  const { profile } = searchContext;

  // Query ESTRITA em PT, cor/tecido garantidos pelo perfil quando a peça
  // não especifica os seus próprios.
  const strict = buildPieceQuery(
    pieceName, searchContext.colorHint, searchContext.categoryKey, searchContext.styleHint, profile,
  );
  const strictLadder = buildPieceQueryLadder(strict, searchContext.categoryKey);

  // Ladder legado em EN — agora também alimentado pelo perfil único.
  const legacyPrimary = buildQueryEN(pieceName, category, profile);
  const legacyLadder = buildProgressiveFallbackQueries(legacyPrimary, pieceName, category, profile);
  const fallbackQueries = uniqueQueries([...strictLadder, ...legacyLadder]);

  console.debug('[query final enviada]', strict.query,
    '| tipo:', strict.meta.tipo, '| corte:', strict.meta.corte, '| cor:', strict.meta.cor,
    '| perfil.cor:', profile.colorEN, '| perfil.tecido:', profile.fabricEN, '| piece:', pieceName);

  const productExclusions = [
    ...(searchContext.strictProductShot ? [
      'magazine', 'cover', 'editorial', 'runway', 'catwalk', 'backstage',
      'collage', 'grid', 'poster', 'banner', 'billboard', 'advertisement', 'ad', 'campaign',
      'watermark', 'logo', 'brand', 'text overlay',
      'portrait', 'face', 'close-up', 'closeup', 'selfie',
      'foot', 'feet', 'toe', 'toes', 'nail', 'pedicure',
      'street style', 'paparazzi', 'celebrity', 'lookbook', 'look book',
      'product on table', 'product in hand', 'holding', 'hand', 'hands',
      'car', 'cart', 'shopping cart', 'wheelbarrow', 'trolley', 'stroller', 'carriage',
    ] : []),
    ...profile.hardNegatives,
  ];

  // Extra safety-net exclusions to avoid objects that frequently appear
  // in non-fashion search results (glassware, food, household items).
  // These are appended after profile.hardNegatives to ensure they are
  // always considered by providers that accept `exclude_terms`.
  const extraProductExclusions = [
    'glass', 'bottle', 'cup', 'drink', 'beverage', 'glassware', 'goblet', 'vase',
    'flower', 'floral', 'food', 'plate', 'table', 'kitchen', 'utensil', 'mug', 'jar',
    'toy', 'car', 'vehicle', 'stroller', 'wheel', 'trolley', 'shopping cart',
    'person', 'people', 'human', 'full body', 'wearing', 'on model', 'mannequin', 'fashion model',
  ];

  const finalExclusions = uniqueQueries([...productExclusions, ...extraProductExclusions]);

  const brokerOptions: BrokerFallbackOptions = {
    diagnosisId,
    mode: 'product',
    category,
    color: strict.nativeColor ?? profile.colorNative,
    providerMode: searchContext.providerMode ?? 'default',
    strictProductShot: Boolean(searchContext.strictProductShot),
    exclusions: finalExclusions,
    metadata: {
      pieceName, category,
      categoryKey: searchContext.categoryKey,
      strictProductShot: Boolean(searchContext.strictProductShot),
      tipo: strict.meta.tipo, corte: strict.meta.corte,
      nativeColor: strict.nativeColor ?? profile.colorNative,
      profileColor: profile.colorEN, profileFabric: profile.fabricEN, profileStyle: profile.styleEN,
    },
  };

  try {
    const providerUrl = await searchRealProvidersFallback(
      fallbackQueries, strict.query, searchContext.excludeUrls ?? null, seed, brokerOptions,
    );
    if (providerUrl) return providerUrl;

    const fallbackPrompt = buildAutoGeneratedImagePrompt({
      pieceName,
      category,
      color: strict.nativeColor ?? profile.colorNative,
      mode: 'product',
      strictProductShot: Boolean(searchContext.strictProductShot),
    });
    const fallbackSeed = (seed ?? hashString(pieceName)) % 9999999;
    // Try local Automatic1111 Stable Diffusion WebUI first (no external API/key)
    try {
      const sdResp = await fetch('http://127.0.0.1:7860/sdapi/v1/txt2img', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: fallbackPrompt,
          width: 512,
          height: 512,
          seed: fallbackSeed,
          steps: 20,
          cfg_scale: 7.0,
          sampler_name: 'Euler a',
        }),
      });
      if (sdResp.ok) {
        const sdJson = await sdResp.json();
        const b64 = Array.isArray(sdJson?.images) && sdJson.images[0] ? sdJson.images[0] : null;
        if (b64) {
          console.log('[useAutoImage] generated image via Automatic1111 local WebUI', { pieceName, category });
          return `data:image/png;base64,${b64}`;
        }
      }
    } catch (e) {
      console.debug('[useAutoImage] Automatic1111 local generation failed', String(e));
    }

    // Fallback to Pollinations (clamped to 512x512)
    const fallbackUrl = buildFastPollinationsUrl(fallbackPrompt, 512, 512, fallbackSeed);
    console.log('[useAutoImage] falling back to free Pollinations generator', { pieceName, category, prompt: fallbackPrompt });
    return fallbackUrl;
  } catch (err) {
    console.warn(`[useAutoImage] search error "${strict.query}"`, err);
    const fallbackPrompt = buildAutoGeneratedImagePrompt({
      pieceName,
      category,
      color: strict.nativeColor ?? profile.colorNative,
      mode: 'product',
      strictProductShot: Boolean(searchContext.strictProductShot),
    });
    const fallbackSeed = (seed ?? hashString(pieceName)) % 9999999;
    return buildFastPollinationsUrl(fallbackPrompt, 800, 800, fallbackSeed);
  }
}

async function fetchClothingImage(
  pieceName: string,
  diagnosisId: string,
  category: string | undefined,
  nonce: number | undefined,
  searchContext: ImageSearchContext,
): Promise<{ url: string | null; fromFallback: boolean }> {
  const key = `${IMAGE_SEARCH_PIPELINE_VERSION}:${diagnosisId}:${normalizeToken(pieceName)}:${normalizeToken(category)}:${normalizeToken(searchContext.categoryKey)}:${nonce ?? 0}`;
  const existing = fetchInFlight.get(key);
  if (existing) return existing.then((u) => ({ url: u, fromFallback: !u }));

  const promise = (async () => {
    const seed = hashString(`${diagnosisId}:${pieceName}:${category ?? ''}:${nonce ?? 0}`);
    const internetUrl = await searchInternetImage(pieceName, diagnosisId, category, seed, searchContext);
    fetchInFlight.delete(key);
    return internetUrl;
  })();

  fetchInFlight.set(key, promise);
  const url = await promise;
  return { url, fromFallback: false };
}

export function useAutoImage(
  pieceName: string | undefined,
  imagesMap?: ImagesMap,
  diagnosisId?: string,
  category?: string,
  _restrictions?: string[],
  options?: { colorHint?: string; strictProductShot?: boolean; categoryKey?: string; providerMode?: ProviderMode },
) {
  // SISTEMA ANTIGO DESABILITADO - Agora usamos apenas diagnosis-image-search
  // Sempre retorna vazio para forçar uso do novo sistema
  return {
    imageUrl: null,
    isLoading: false,
    hasFailed: false,
    retry: () => {},
    pdfKey: null,
  };

  const imageCtx = useSectionImagesContext();
  const normalizedName = useMemo(() => normalizeToken(pieceName), [pieceName]);

  // Perfil único do diagnóstico — memoizado internamente por diagnosisId,
  // então chamar isso em 50 componentes de peça diferentes não recalcula
  // nada nem gera valores divergentes entre si.
  const profile = useMemo(() => {
    if (!diagnosisId) return null;
    const d = imageCtx.diagnostic as unknown as Record<string, unknown> | undefined;
    return getDiagnosisImageProfile({
      diagnosisId,
      colorAnalysis: null,
      styleAnalysis: d ? { estiloPersonalidade: (d as any).estiloPersonalidade } : null,
      questionnaire: (imageCtx.questionnaire as Record<string, unknown> | null) ?? null,
      skinTone: d ? ((d as any).tomDePele ?? null) : null,
    });
  }, [diagnosisId, imageCtx.diagnostic, imageCtx.questionnaire]);

  const searchContext = useMemo<ImageSearchContext | null>(() => {
    if (!profile) return null;
    const d = imageCtx.diagnostic as any;
    const styleHint = d ? (STYLE_EN[d.estiloPersonalidade] || d.estiloPersonalidade) : undefined;
    const paletteHint = d
      ? (SEASON_PALETTE[d.tomDePele]?.[d.estiloPersonalidade] || STYLE_PALETTE[d.estiloPersonalidade])
      : undefined;
    const occasionHint = d ? (OCCASION_EN[d.ocasiao] || d.ocasiao) : undefined;
    return {
      colorHint: options?.colorHint,
      // Default to strict product-shot behavior to prioritize isolated
      // product photography over editorial/packaging results.
      strictProductShot: options?.strictProductShot ?? true,
      categoryKey: options?.categoryKey,
      providerMode: options?.providerMode ?? 'default',
      styleHint,
      paletteHint,
      occasionHint,
      excludeUrls: imageCtx.usedImageUrls ? Array.from(imageCtx.usedImageUrls).slice(-60) : [],
      profile,
    };
  }, [profile, imageCtx.diagnostic, imageCtx.usedImageUrls, options?.categoryKey, options?.colorHint, options?.strictProductShot, options?.providerMode]);

  const [fallbackUrl, setFallbackUrl] = useState<string | null>(null);
  const [hasFailed, setHasFailed] = useState(false);
  const [isFetching, setIsFetching] = useState(false);
  const [attempt, setAttempt] = useState(0);
  const fetchedRef = useRef<string | null>(null);

  const staticUrl = useMemo(() => {
    if (!diagnosisId || !normalizedName) return null;
    const cacheScope = options?.strictProductShot ? `piece_catalog_${IMAGE_SEARCH_PIPELINE_VERSION}_color_type:${normalizeToken(options?.categoryKey)}` : `piece_${IMAGE_SEARCH_PIPELINE_VERSION}`;
    return getStaticDiagnosticImage(`${diagnosisId}:${cacheScope}:${normalizedName}`);
  }, [diagnosisId, normalizedName, options?.categoryKey, options?.strictProductShot]);

  const cachedUrl = useMemo(() => {
    if (staticUrl) return staticUrl;
    if (!normalizedName || !imagesMap || imagesMap.size === 0) return null;
    return imagesMap.get(normalizedName) || null;
  }, [staticUrl, normalizedName, imagesMap]);

  useEffect(() => {
    if (!diagnosisId || !normalizedName || !cachedUrl) return;
    const cacheScope = options?.strictProductShot ? `piece_catalog_${IMAGE_SEARCH_PIPELINE_VERSION}_color_type:${normalizeToken(options?.categoryKey)}` : `piece_${IMAGE_SEARCH_PIPELINE_VERSION}`;
    setStaticDiagnosticImage(`${diagnosisId}:${cacheScope}:${normalizedName}`, cachedUrl);
  }, [diagnosisId, normalizedName, cachedUrl, options?.categoryKey, options?.strictProductShot]);

  useEffect(() => {
    setFallbackUrl(null);
    setHasFailed(false);
    fetchedRef.current = null;
  }, [normalizedName, diagnosisId]);

  useEffect(() => {
    if (imageCtx.isPdfMode) {
      if (!cachedUrl && !hasFailed) setHasFailed(true);
      return;
    }
    if (!normalizedName || !pieceName || !diagnosisId || cachedUrl || !searchContext) return;

    const key = `${IMAGE_SEARCH_PIPELINE_VERSION}:${diagnosisId}:${normalizedName}:${normalizeToken(category)}:${attempt}`;
    if (fetchedRef.current === key) return;
    fetchedRef.current = key;

    setIsFetching(true);
    setHasFailed(false);
    fetchClothingImage(pieceName, diagnosisId, category, attempt > 0 ? attempt : undefined, searchContext).then(({ url: finalUrl, fromFallback }) => {
      const cacheScope = options?.strictProductShot ? `piece_catalog_${IMAGE_SEARCH_PIPELINE_VERSION}_color_type:${normalizeToken(options?.categoryKey)}` : `piece_${IMAGE_SEARCH_PIPELINE_VERSION}`;
      if (finalUrl) {
        if (!fromFallback && !isLocalFallbackImage(finalUrl)) {
          setStaticDiagnosticImage(`${diagnosisId}:${cacheScope}:${normalizedName}`, finalUrl);
          imageCtx.usedImageUrls?.add(finalUrl);
        }
        setFallbackUrl(finalUrl);
        setHasFailed(false);
        if (!fromFallback && !isLocalFallbackImage(finalUrl)) imageCtx.refreshImages?.();
      } else {
        console.warn('[useAutoImage] busca de peça falhou; sem imagem definitiva', { pieceName, category });
        setFallbackUrl(null);
        setHasFailed(true);
      }
      setIsFetching(false);
    }).catch((err) => {
      console.warn('[useAutoImage] falha protegida na busca de imagem; mantendo a página estável', err);
      setFallbackUrl(null);
      setHasFailed(true);
      setIsFetching(false);
    });
  }, [pieceName, normalizedName, cachedUrl, diagnosisId, category, attempt, searchContext, imageCtx.usedImageUrls, imageCtx.isPdfMode, hasFailed, options?.categoryKey, options?.strictProductShot]);

  const retry = useCallback(() => {
    fetchedRef.current = null;
    setFallbackUrl(null);
    setHasFailed(false);
    setAttempt((v) => v + 1);
  }, []);

  return {
    imageUrl: cachedUrl || fallbackUrl,
    isLoading: isFetching,
    hasFailed,
    retry,
    pdfKey: normalizedName,
    pieceName,
  };
}
