import { describe, expect, it } from 'vitest';
import { buildAutoGeneratedImagePrompt, buildFastPollinationsUrl, buildPollinationsUrl } from './imageService';

describe('buildAutoGeneratedImagePrompt', () => {
  it('cria um prompt de produto isolado para peças de roupa', () => {
    const prompt = buildAutoGeneratedImagePrompt({
      pieceName: 'jaqueta jeans',
      category: 'casaco',
      color: 'azul',
      mode: 'product',
      strictProductShot: true,
    });

    expect(prompt).toContain('jaqueta jeans');
    expect(prompt).toContain('isolated product shot');
    expect(prompt).toContain('white background');
    expect(prompt).toContain('fashion');
  });
});

describe('buildFastPollinationsUrl', () => {
  it('usa o endpoint turbo para resposta mais rápida', () => {
    const url = buildFastPollinationsUrl('blazer feminino', 800, 800, 42);
    expect(url).toContain('model=turbo');
    expect(url).toContain('enhance=false');
  });

  it('corta dimensões para 512 por confiabilidade do endpoint', () => {
    const url = buildFastPollinationsUrl('blazer feminino', 800, 900, 42);
    expect(url).toContain('width=512');
    expect(url).toContain('height=512');
  });
});

describe('buildPollinationsUrl', () => {
  it('corta dimensões para 512 para evitar falhas em tamanhos grandes', () => {
    const url = buildPollinationsUrl('blazer feminino', 1024, 1024, 42);
    expect(url).toContain('width=512');
    expect(url).toContain('height=512');
  });
});
